// Auto-generated by scripts/sync-vidsrc-latest.ts
// This file may be intentionally kept small in git to avoid huge diffs.
// Run the sync script to populate locally if needed.

export interface VidsrcLatestMovie {
  imdb_id: string;
  tmdb_id: string;
  title: string;
  quality: string;
  time_added: string;
  embed_url: string;
  embed_url_tmdb: string;
}

export const VID_SRC_LATEST_MOVIES: VidsrcLatestMovie[] = [];
