#!/usr/bin/env node
/**
 * Daily sync for:
 * - app/data/vidsrcLatestMovies.ts (movies latest feed)
 * - app/data/tvSeriesIds.ts (TV imdb ids)
 *
 * Usage:
 *   node scripts/daily-sync.js
 *   node scripts/daily-sync.js --recent --pages=6 --batch=5
 *   node scripts/daily-sync.js --recent --pages=6 --batch=5 --watch=1440
 *   node scripts/daily-sync.js --skip-tv --recent --pages=3 --batch=2
 */

const fs = require("fs");
const path = require("path");

const MOVIES_FIRST_PAGE_URL = (p) =>
  `https://vidsrc-embed.ru/movies/latest/page-${p}.json`;
const TV_IDS_URL = "https://vidsrc.me/ids/tv_imdb.txt";

function argFlag(name) {
  return process.argv.includes(`--${name}`);
}

function argValue(name, fallback) {
  const p = process.argv.find((x) => x.startsWith(`--${name}=`));
  if (!p) return fallback;
  const v = p.slice(name.length + 3);
  const n = Number.parseInt(v, 10);
  return Number.isFinite(n) ? n : fallback;
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function uniq(arr) {
  const out = [];
  const seen = new Set();
  for (const x of arr) {
    if (!x || seen.has(x)) continue;
    seen.add(x);
    out.push(x);
  }
  return out;
}

function safeJson(v) {
  try {
    return JSON.stringify(v, null, 2);
  } catch {
    return "null";
  }
}

async function fetchJson(url) {
  const res = await fetch(url, {
    cache: "no-store",
    headers: {
      "User-Agent":
        "Mozilla/5.0 (compatible; movies-site-bot/1.0; +https://example.invalid)",
      Accept: "application/json",
    },
  });
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
  return res.json();
}

async function fetchText(url) {
  const res = await fetch(url, {
    cache: "no-store",
    headers: {
      "User-Agent":
        "Mozilla/5.0 (compatible; movies-site-bot/1.0; +https://example.invalid)",
      Accept: "text/plain",
    },
  });
  if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
  return res.text();
}

function parseMovieItems(pageJson) {
  const arr = Array.isArray(pageJson?.result) ? pageJson.result : [];
  return arr
    .map((x) => ({
      imdb_id: String(x?.imdb_id || "").trim(),
      tmdb_id: String(x?.tmdb_id || "").trim(),
      title: String(x?.title || "").trim(),
      quality: String(x?.quality || "").trim(),
      time_added: String(x?.time_added || "").trim(),
      embed_url: String(x?.embed_url || "").trim(),
      embed_url_tmdb: String(x?.embed_url_tmdb || "").trim(),
    }))
    .filter((x) => x.imdb_id && x.time_added);
}

function parseTimeAdded(s) {
  // vidsrc: "YYYY-MM-DD HH:mm:ss"
  const iso = String(s || "").replace(" ", "T") + "Z";
  const t = Date.parse(iso);
  return Number.isFinite(t) ? t : 0;
}

async function syncMovies({ pages, batch }) {
  const all = [];
  let p = 1;
  while (p <= pages) {
    const chunk = [];
    for (let i = 0; i < batch && p + i <= pages; i++) chunk.push(p + i);
    const results = await Promise.all(
      chunk.map(async (pageNum) => {
        const url = MOVIES_FIRST_PAGE_URL(pageNum);
        const j = await fetchJson(url);
        return parseMovieItems(j);
      })
    );
    for (const items of results) all.push(...items);
    p += chunk.length;
  }

  // Deduplicate by imdb_id, keep most recent time_added
  const byId = new Map();
  for (const m of all) {
    const prev = byId.get(m.imdb_id);
    if (!prev || parseTimeAdded(m.time_added) > parseTimeAdded(prev.time_added)) {
      byId.set(m.imdb_id, m);
    }
  }
  const movies = Array.from(byId.values()).sort(
    (a, b) => parseTimeAdded(b.time_added) - parseTimeAdded(a.time_added)
  );
  return movies;
}

function writeVidsrcLatestMoviesTs(movies) {
  const outPath = path.join(process.cwd(), "app", "data", "vidsrcLatestMovies.ts");
  const updated = new Date().toISOString();
  const lines = [];
  lines.push(`// Auto-generated by scripts/daily-sync.js`);
  lines.push(`// Source: https://vidsrc-embed.ru/movies/latest/page-*.json`);
  lines.push(`// Total movies: ${movies.length}`);
  lines.push(`// Updated: ${updated}`);
  lines.push(``);
  lines.push(`export interface VidsrcLatestMovie {`);
  lines.push(`  imdb_id: string;`);
  lines.push(`  tmdb_id: string;`);
  lines.push(`  title: string;`);
  lines.push(`  quality: string;`);
  lines.push(`  time_added: string;`);
  lines.push(`  embed_url: string;`);
  lines.push(`  embed_url_tmdb: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const VID_SRC_LATEST_MOVIES: VidsrcLatestMovie[] = ${safeJson(movies)};`);
  lines.push(``);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  return outPath;
}

function writeTvSeriesIdsTs(ids) {
  const outPath = path.join(process.cwd(), "app", "data", "tvSeriesIds.ts");
  const updated = new Date().toISOString();
  const lines = [];
  lines.push(`// TV Series IDs from VidSrc`);
  lines.push(`// Total: ${ids.length} series`);
  lines.push(`// Source: ${TV_IDS_URL}`);
  lines.push(`// Last updated: ${updated}`);
  lines.push(``);
  lines.push(`export const TV_SERIES_IDS: string[] = ${safeJson(ids)};`);
  lines.push(``);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  return outPath;
}

async function syncTvIds() {
  const txt = await fetchText(TV_IDS_URL);
  const ids = uniq(
    txt
      .split(/\r?\n/g)
      .map((x) => x.trim())
      .filter((x) => /^tt\d{6,10}$/i.test(x))
  );
  return ids;
}

async function runOnce() {
  const recent = argFlag("recent");
  const pages = argValue("pages", recent ? 6 : 1);
  const batch = argValue("batch", 5);
  const skipTv = argFlag("skip-tv");

  console.log(`[daily-sync] recent=${recent} pages=${pages} batch=${batch} skipTv=${skipTv}`);

  const movies = await syncMovies({ pages, batch });
  const moviesFile = writeVidsrcLatestMoviesTs(movies);
  console.log(`[daily-sync] wrote ${moviesFile} (${movies.length} movies)`);

  if (!skipTv) {
    const tvIds = await syncTvIds();
    const tvFile = writeTvSeriesIdsTs(tvIds);
    console.log(`[daily-sync] wrote ${tvFile} (${tvIds.length} ids)`);
  } else {
    console.log(`[daily-sync] skip tv ids`);
  }
}

async function main() {
  const watchMins = argValue("watch", 0);
  if (watchMins > 0) {
    const intervalMs = Math.max(60_000, watchMins * 60_000);
    // eslint-disable-next-line no-constant-condition
    while (true) {
      try {
        await runOnce();
      } catch (e) {
        console.error("[daily-sync] error:", e?.stack || e);
      }
      console.log(`[daily-sync] sleeping ${Math.round(intervalMs / 1000)}s`);
      await sleep(intervalMs);
    }
  }
  await runOnce();
}

main().catch((e) => {
  console.error("[daily-sync] fatal:", e?.stack || e);
  process.exit(1);
});

